### ISSUE TITLE
Modelのフィールドを拡充する。

### ISSUE THREAD

**Issue by kuriyama-dcinc** [denso-create/LightningReview-RevxFile#1]
- [x] Reviewのフィールド
- [x] Issueのフィールド
- [x] Documentのフィールド
- [x] OutlineNodeのフィールド

**Comment by yus-sasaki** [comment]
## Reviewのフィールド拡充
コミット：https://github.com/denso-create/LightningReview-ReviewFile/commit/cbf2efec5cedf4565bc37e2eac7e2c5afe0e6152 https://github.com/denso-create/LightningReview-ReviewFile/commit/f340b1b2918651a3a1d96b2121d5931bbd8fa20b
LRのExtensionFrameworkで公開しているプロパティを参考にReviewとしては基本設定タブと予実タブの情報が取得できるように拡充。
- 追加したフィールド
EndCondition(終了条件)、ProjectName(プロジェクト名)、ProjectCode(プロジェクトコード)
ActualScale(実績成果量)、IssueCountOfGoal(目標件数)、IssueCountOfActual(実績件数)
- 未実現のフィールド
xmlの階層が深く、現時点ではユーザの主な収集対象ではないため以下のフィールドは未実装。
Status(ステータス)、Domain(ドメイン)、ReviewType(レビュー種別)、ReviewStyle(レビュー形式)
以下のカードに分離する
https://github.com/denso-create/LightningReview-ReviewFile/projects/1#card-55167842

## Documentのフィールド拡充
コミット：https://github.com/denso-create/LightningReview-ReviewFile/commit/eeb813a369aea385be45a904a6198b90ea5d7e38
LRのExtensionFrameworkで公開しているプロパティを参考に拡充
- 追加したフィールド
AbsolutePath (絶対パス)、ApplicationType(アプリケーションタイプ)

## コメントの付与
他の実装中にも逐次コメントは記載しておりますが、下記コミットで付与しております。
文字化けしていたので修正：https://github.com/denso-create/LightningReview-ReviewFile/commit/ded0e4da3270dedb243270fc8c5445428aa18c5c
サマリー記載および微修正：https://github.com/denso-create/LightningReview-ReviewFile/commit/713283332fef1004debef43cf8eda57c12617d1e
region追加および並び替え：https://github.com/denso-create/LightningReview-ReviewFile/commit/f71920dae596a824383e0ff87c0d847a5c8ffd48

**Comment by yus-sasaki** [comment]
## Issueのフィールド拡充
コミット：https://github.com/denso-create/LightningReview-ReviewFile/commit/3ae31320e4e8c9fc8eae6b83042fe6548a86da86 f854b8e1ee0a7b89870881a2da839c9c4d3fba33
LRのExtensionFrameworkで公開しているプロパティを参考に拡充
- 追加したフィールド
CorrectionPolicy(修正方針)
SendingBackReason(差し戻し理由)
OutlineName(関連づいているアウトライン名)
RootOutlineName(関連づいているドキュメント名)
DateReported(報告日)
DueDate(期日)
DateFixed(修正日)
DateConfirmed(確認日)

## OutlineNodeのフィールド拡充
- 未実現のフィールド
xmlから直接取得できる要素ではなく、Outlineはユーザの主な収集対象ではないため、以下のフィールドは未実装
PhysicalLocationXml(物理的位置)、Path(アウトラインパス)、Level(階層の深さ)
以下のカードに分離する
https://github.com/denso-create/LightningReview-ReviewFile/projects/1#card-55167991

**Comment by yus-sasaki** [comment]
## ReviewFileToJsonService.Modelsの拡充
ReviewFileToJsonServiceのModelsについても同じように拡充しました（ReviewとIsasueクラス）
コミット：https://github.com/denso-create/LightningReview-ReviewFile/commit/78816649f120a8cb04dce2459f036d1a55c9f0c6

## DateTime型のフィールドの異常系の処理を追加
日付系(期日や修正日時等)の要素を空にした状態のレビューファイルを読み込んだ際に例外が出る場合があるため、そのような場合はnullを返すフェールセーフ処理を追加しました
コミット：https://github.com/denso-create/LightningReview-ReviewFile/commit/5e534bc2d70ca8a34b8f6a595aeb2097de460a01 https://github.com/denso-create/LightningReview-ReviewFile/commit/6732f952289665b2630fbac31530a9fc3d6233eb https://github.com/denso-create/LightningReview-ReviewFile/commit/6732f952289665b2630fbac31530a9fc3d6233eb

**Comment by kojimadev** [comment]
上記の通り、優先度の低い未実現のフィールドは以下のタスクに分離済み。
https://github.com/denso-create/LightningReview-ReviewFile/projects/1#card-55167991
https://github.com/denso-create/LightningReview-ReviewFile/projects/1#card-55167842

それ以外は、以下のプルリクで完了済みなのでクローズします。
https://github.com/denso-create/LightningReview-ReviewFile/pull/6
