### ISSUE TITLE
C#のバージョンは7.3とする

### ISSUE THREAD

**Issue by yus-sasaki** [denso-create/LightningReview-RevxFile#13]
- C#のバージョンは7.3 , dotNET Standard 2.0のデフォルト値にする
null許容型は使わない。
- readmeに 対応するプラットフォームのバージョンを各パッケージごとに記載する
（他のDensoCreate.XXXを参照すること）

**Comment by kojimadev** [comment]
https://github.com/denso-create/LightningReview-ReviewFile/commit/0d9f15a536548a89d219214b66b64c19ac5665ee
上記で完了済み
