### ISSUE TITLE
全体的にコメントを付与する。

### ISSUE THREAD

**Issue by kuriyama-dcinc** [denso-create/LightningReview-RevxFile#2]

**Comment by yus-sasaki** [comment]
## Readme.mdの拡充
CLIでのJSONの出力フォーマットの説明の拡充 579ef21a3ab15dbdd5921498c45d9db917231b0b
ReviewやIssueの要素にアクセスする例の拡充 639bda0fee16fbbc2264ed9cdc2ec5ade7b22610

## JSONの出力オプションを日本語がUnicodeエスケープされないように変更
JSONのシリアライズ設定に1行追加し、コードおよびReadmeに設定についてのことを明記 b4e1820f7c8f5a1844b9d30b521e2695d5bb7622

出力オプションとしてUnicodeエスケープを切り替えられるように変更
- ReviewFileToJsonExporter.Exportの引数にunescapedUnicodeを追加およびCLIのオプションに追加 9fa9380620df50c92fd87263679da85b889d66ac
- Readmeに追記 2a5e1f22afedae7ea767c6b1d451d79379d27536 

## XMLコメントがなく警告を受けている件の解消
publish-nugetを実行している際に警告がされておりその解消を行う 
ActionのAnnotations参照： https://github.com/denso-create/LightningReview-ReviewFile/actions/runs/592384079
警告を受けていたXMLコメントがない箇所のサマリーを記載しました 4e8ec5f33b2ff2c17cf7cc89b0fe59bd50f1c173 2c8ff5fb0d5392ce8203b080e7a4e1aa9750e835 0425fbd41da7989977fac32a7eed8119ba1cc588

## デフォルトをmainブランチに改名
デフォルトブランチをmasterからmainに改名しました。
下記の記事を参考にgithubのSettingsから設定を行いました。
https://dev.classmethod.jp/articles/how-to-change-github-repos-default-branch-name/

改名に関連する修正（YMLファイルおよびReadmeのパスをmainに変更） 869446f537f0e3afed04c106b9417a0be342e481

## 異常系のテストの拡充
Modelのテストは現在、正常系のみ確認しておりますが、レビューファイルとしては未設定が可能なフィールドが存在し、未設定の場合を念の為確認するテストが必要だと判断。
ReviewFileReader.Readなどのメソッドも同様で異常値の際にエラーメッセージが期待値通り出るかテストする必要があると判断。
⇨別のissueに分離しました　https://github.com/denso-create/LightningReview-ReviewFile/issues/10

**Comment by kojimadev** [comment]
https://github.com/denso-create/LightningReview-ReviewFile/pull/11
上記のプルリクで完了済
