### ISSUE TITLE
masterブランチにpushしたらnugetで公開するようにGithub Actionsで自動化する。

### ISSUE THREAD

**Issue by kuriyama-dcinc** [denso-create/LightningReview-RevxFile#3]
* github actionsでnugetへのpushを自動化する。

* 参考記事（他にもあるので調べる事）
 https://netlicensing.medium.com/publish-nuget-packages-using-github-actions-9ac5e97d07d4

**Comment by yus-sasaki** [comment]
## 調べた結果
個人的なNugetパッケージを公開し動作確認したところ、自動でNugetが公開されることを確認できました。
調べて試したことは下記記事にまとめました。
https://qiita.com/yusuke-sasaki/items/c75e32aadcd297461ef7

APIキーの部分だけ設定いただければ自動でできるようになるかと思います。

**Comment by kojimadev** [comment]
以下のプルリクで完了済みなのでクローズします。
https://github.com/denso-create/LightningReview-ReviewFile/pull/5
