### ISSUE TITLE
Modelのユニットテストを拡充する

### ISSUE THREAD

**Issue by yus-sasaki** [denso-create/LightningReview-RevxFile#4]
- [x] Review
- [x] Issue
- [x] Document

**Comment by yus-sasaki** [comment]
## Reviewのテスト拡充
コミット：https://github.com/denso-create/LightningReview-ReviewFile/commit/30b64c20868f10bf1017ed0913f10be71c3f95d4 https://github.com/denso-create/LightningReview-ReviewFile/commit/39a90731a084773d0d60491d9b0c810bdd5a8161
拡充したフィールドについて正常系を確認する1ケースずつを拡充した。

## Issueのテスト拡充
コミット：https://github.com/denso-create/LightningReview-ReviewFile/commit/95611c13210cbe72120d1d4bda3acf5485eeac39
拡充したフィールドについて正常系を確認する1ケースずつを拡充した。

## Documentのテスト拡充
コミット：https://github.com/denso-create/LightningReview-ReviewFile/commit/6ceef9b750cb9ad6ab63619a3a563059e70fdfeb
拡充したフィールドについて正常系を確認する1ケースずつを拡充した。

**Comment by kojimadev** [comment]
以下のプルリクで完了済みのためクローズします。
https://github.com/denso-create/LightningReview-ReviewFile/pull/6
